# Generated by Django 4.2.7 on 2023-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="title",
            field=models.CharField(default="sample", max_length=200),
            preserve_default=False,
        ),
    ]
