# Generated by Django 4.2.7 on 2023-11-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_userfile_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="answer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
